apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: app2
  namespace: argo-cd
spec:
  destination:
    name: in-cluster
    namespace: app2
  project: default
  source:
    plugin:
      name: avp-helm-args
      env:
        - name: ARGOCD_APP_NAME
          value: app1
        - name: ARGOCD_APP_NAMESPACE  
          value: demo
        - name: HELM_ARGS
          value: "-f values-test.yaml"
    path: app1
    repoURL: 'https://github.com/Hitham07/target'
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 30s
      limit: 20
