apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: <path:kv-v2/data//service-api#APP_ENCRYPTION_PASSWORD>
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80



