name: Add Pull Request Environment

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true




jobs:
  get-pull-request-environment-id:
    name: get-pull-request-environment-id
    runs-on: ubuntu-latest
    outputs:
      ID: ${{ steps.set_environment_id.outputs.ID }}
    steps:
      - name: Get pull request environment ID
        run: |
          echo ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
          sleep 400

