name: Add Pull Request Environment

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main


jobs:
  get-pull-request-environment-id:
    name: get-pull-request-environment-id
    runs-on: ubuntu-latest
    outputs:
      ID: ${{ steps.set_environment_id.outputs.ID }}
    steps:

      - name: Get pull request environment ID
        id: set_environment_id
        run: |
          id=$(echo "${{ github.event.repository.name }}-${{ github.event.number }}-test" | sed 's/^kuberex-//; s/service/svc/')
          echo "ID=$id" >> $GITHUB_ENV
          echo "ID=$id" >> $GITHUB_OUTPUT

      - name: Display SHA for Pull Requests
        run: |
          echo "The SHA for the pull request is: ${{ github.event.pull_request.head.sha }}"

  extract-pr-number:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ github.event.pull_request.number }}  # Set PR number as an output

    steps:
      - name: Set PR Number
        run: |
          echo "PR Number: ${{ github.event.pull_request.number }}"number }}"

          
  # deploy-pull-request-environment:
  #   needs: [ get-pull-request-environment-id ]
  #   uses: area99-ai/kuberex-workflows/.github/workflows/add-pull-request-environment-template.yaml@master
  #   secrets: inherit # pragma: allowlist secret
  #   with:
  #     ENVIRONMENT_ID: ${{ needs.get-pull-request-environment-id.outputs.ID }}
      