name: Microservice Workflow

on:
  push:
    branches:
      - main

# jobs:
#   call-shared-workflow:
#     uses: hitham07/source/.github/workflows/shared.yaml@main
#     with:
#       example_input: 'some-value'
 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Run tests
      run: |
        echo ${{ github.event }}
