name: Pull Request Workflow

on:
  pull_request:
    types: [synchronize]
    branches:
      - main
  workflow_call:
    
jobs:
  get-pull-request-environment-id:
    name: get-pull-request-environment-id
    runs-on: ubuntu-latest
    outputs:
      ID: ${{ steps.set_environment_id.outputs.ID }}
    steps:

            
      - name: Get pull request environment ID
        id: set_environment_id
        run: |
          id=$(echo "${{ github.event.repository.name }}-${{ github.event.number }}-test" | sed 's/^kuberex-//; s/service/svc/')
          echo "ID=$id" >> $GITHUB_ENV
          echo "ID=$id" >> $GITHUB_OUTPUT


  display-GIT_SHA:
    needs: [ get-pull-request-environment-id]
    runs-on: ubuntu-latest
    steps:
      - name: Display SHA
        run: |
          echo "The SHA is: ${{ github.event.number }}"