name: Release Workflow 

on:
  workflow_run:
    workflows: ["Merge to Master"]
    types:
      - completed
  push:
    branches:
      - main


      

jobs:
  create-github-release:
    name: Bump version and push tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Bump version and push tag
      #   id: tag_version
      #   uses: mathieudutour/github-tag-action@v6.2
      #   with:
      #     github_token: ${{ secrets.TEST }}
      #     default_bump: minor

      # - name: Create a GitHub release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     tag: ${{ steps.tag_version.outputs.new_tag }}
      #     name: Release ${{ steps.tag_version.outputs.new_tag }}
      #     body: ${{ steps.tag_version.outputs.changelog }}
      #     generateReleaseNotes: true
      #     token:  ${{ secrets.TEST }}
      #     artifacts: "source-0.5.0.tar.gz"

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: proto-artifact
      #     path: proto

      - uses: actions/download-artifact@v4
        with:
          name: proto-artifact
          github-token: ${{ secrets.TEST }} 
          repository: Hitham07/source
          path: destination

      - name: Display structure of downloaded files
        run: ls -R destination
          