name: Release Workflow 

on:
  workflow_run:
    workflows: ["Merge to Master"]
    types:
      - completed
  push:
    branches:
      - main
      
jobs:
  get-github-release:
    name: get-github-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TEST }} 

      - name: Create server1 directory
        env:
          GITHUB_TOKEN: ${{ secrets.TEST }} 
        run: ./download-release-asset.sh 

      - name: Commit and push changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ toJson(github.event.head_commit.author.email) }}"
          git add .
          git commit --allow-empty -m "update "
          git push origin main
